name: Parse PDF

on:
  push:
    paths:
      - 'pdf/upload.pdf'

jobs:
  parse:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run parser
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: python parser.py
